server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,heapdump,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState,diskSpace,mongo

spring:
  data:
    mongodb:
      uri: mongodb://${DB_HOST:localhost}:27017/wishlist


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html